name: UI Tests

permissions:
  contents: write
  
on:
  push:
  pull_request:

jobs:
  selenium-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install allure-pytest

      - name: Run tests
        run: |
          pytest --alluredir=allure-results

      - name: Upload Allure Results (Actions UI)
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results

      - name: Generate Allure Report
        run: |
          wget https://github.com/allure-framework/allure2/releases/download/2.29.0/allure-2.29.0.tgz
          tar -xzf allure-2.29.0.tgz
          ./allure-2.29.0/bin/allure generate allure-results -o allure-report --clean

      - name: Deploy Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
          force_orphan: true
